[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "psutil==5.9.0",
]

[tool.black]
line_length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
